version: 2.1
jobs:
  build:
    parameters:
      Pipeline Number:
        type: integer
        default: 8
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'Adding something'
            echo 'SOMETHING ELSE'
  deploy:
    parameters:
      Pipeline Number:
        type: integer
        default: 8
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'Adding something'
            echo 'SOMETHING ELSE'

